import {
  Product,
  Review,
  Cluster,
  Alert,
  ActionItem,
  TimelinePoint,
  ReputationStats,
  IssueStats,
  ResponseStats,
} from "./types";

// ── Product ──
export const product: Product = {
  id: "pirate-ships",
  name: "Pirate Ships: Build and Fight",
  packageId: "com.example.pirateships",
  platform: "google_play",
  rating: 4.49,
  totalReviews: 15420,
};

// ── Reputation / Issue / Response Stats ──
export const reputationStats: ReputationStats = {
  currentRating: 4.49,
  ratingTrend: -0.03,
  lowRatingShare: 0.12,
  lowRatingShareChange: 0.02,
};

export const issueStats: IssueStats = {
  newClusters: 3,
  spikeCount: 2,
  criticalCount: 1,
};

export const responseStats: ResponseStats = {
  unansweredPercent: 67,
  unansweredNegatives: 34,
  totalUnanswered: 189,
};

// ── Timeline (7 days) ──
export const timelineData: TimelinePoint[] = [
  { date: "2026-02-05", negativeReviews: 8, bugReports: 3, alerts: 0, totalReviews: 42 },
  { date: "2026-02-06", negativeReviews: 11, bugReports: 5, alerts: 1, totalReviews: 48 },
  { date: "2026-02-07", negativeReviews: 9, bugReports: 4, alerts: 0, totalReviews: 39, releaseVersion: "1.38.2" },
  { date: "2026-02-08", negativeReviews: 22, bugReports: 9, alerts: 2, totalReviews: 55 },
  { date: "2026-02-09", negativeReviews: 19, bugReports: 7, alerts: 1, totalReviews: 51 },
  { date: "2026-02-10", negativeReviews: 15, bugReports: 6, alerts: 0, totalReviews: 44 },
  { date: "2026-02-11", negativeReviews: 13, bugReports: 5, alerts: 0, totalReviews: 40 },
];

// ── Reviews (50 mock reviews based on real report data) ──
export const reviews: Review[] = [
  { id: "r1", productId: "pirate-ships", rating: 1, text: "AUTOPLAY AND FORCED ADS. This game falls in the forced adds category. After level 10-15, the ad frequency becomes unbearable. It's a cash grab.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "monetization", sentiment: "negative", themes: ["Aggressive Monetization & Forced Ads"], severity: 5, hasReply: false, createdAt: "2026-02-10T14:32:00Z" },
  { id: "r2", productId: "pirate-ships", rating: 1, text: "As if their monetization isn't predatory enough, they force ads after level 15. Every single battle ends with a 30 second unskippable ad.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "ads", sentiment: "negative", themes: ["Aggressive Monetization & Forced Ads"], severity: 5, hasReply: false, createdAt: "2026-02-10T11:15:00Z" },
  { id: "r3", productId: "pirate-ships", rating: 2, text: "Do not make an in game purchase. Made a small in game purchase b/c I was enjoying the game. Shortly after the purchase, the developers tried taking 20+ purchases from my credit card. DO NOT MAKE A IN GAME PURCHASE.", lang: "en", country: "US", appVersion: "1.38.1", category: "bug", subcategory: "payment", sentiment: "negative", themes: ["Monetization & Payment Issues"], severity: 5, hasReply: true, createdAt: "2026-02-09T09:45:00Z" },
  { id: "r4", productId: "pirate-ships", rating: 3, text: "It is a fun simple pirate game but I am waiting to see how much harder it will get as I progress to push me to spend lots of $$$$ to enjoy it.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "monetization", sentiment: "mixed", themes: ["Monetization & Payment Issues"], severity: 3, hasReply: false, createdAt: "2026-02-09T16:20:00Z" },
  { id: "r5", productId: "pirate-ships", rating: 1, text: "Developers constantly change the parameters of the game in a pathetic attempt to get you to spend more money. Ships now cost north of 2 million while I make 10k per battle.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "balance", sentiment: "negative", themes: ["Monetization & Pay-to-Win Balance"], severity: 4, hasReply: false, createdAt: "2026-02-08T08:30:00Z" },
  { id: "r6", productId: "pirate-ships", rating: 1, text: "Ships now cost north of 2 million. While I make 10k per battle... As a f2p it is insanely hard to get the grub for ships. The game has become unplayable for free players.", lang: "en", country: "CA", appVersion: "1.38.2", category: "complaint", subcategory: "progression", sentiment: "negative", themes: ["Monetization & Pay-to-Win Balance"], severity: 4, hasReply: false, createdAt: "2026-02-08T12:45:00Z" },
  { id: "r7", productId: "pirate-ships", rating: 2, text: "Very fun game, obvious p2w aspects. If you don't spend money, you will be stuck behind paywalls after level 30.", lang: "en", country: "GB", appVersion: "1.38.2", category: "complaint", subcategory: "monetization", sentiment: "negative", themes: ["Pay-to-Win Mechanics"], severity: 4, hasReply: false, createdAt: "2026-02-08T15:00:00Z" },
  { id: "r8", productId: "pirate-ships", rating: 1, text: "Please make fair match making as one player is on 30th level he has to play against a mighty 36 or more higher level player. It makes PvP pointless.", lang: "en", country: "IN", appVersion: "1.38.2", category: "complaint", subcategory: "matchmaking", sentiment: "negative", themes: ["Pay-to-Win Mechanics", "Matchmaking & Fair Play"], severity: 4, hasReply: false, createdAt: "2026-02-08T10:30:00Z" },
  { id: "r9", productId: "pirate-ships", rating: 1, text: "They added more ads and then offered a $16 package to make them go away. That's some sleazy business practice right there.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "ads", sentiment: "negative", themes: ["Aggressive Monetization & Ad Strategy"], severity: 4, hasReply: false, createdAt: "2026-02-07T14:00:00Z" },
  { id: "r10", productId: "pirate-ships", rating: 1, text: "Forced ads nonsense. I can't even play 2 minutes without watching an ad. This is the worst I've seen in any mobile game.", lang: "en", country: "AU", appVersion: "1.38.2", category: "complaint", subcategory: "ads", sentiment: "negative", themes: ["Aggressive Monetization & Ad Strategy", "Excessive & Intrusive Ads"], severity: 4, hasReply: false, createdAt: "2026-02-07T09:15:00Z" },
  { id: "r11", productId: "pirate-ships", rating: 1, text: "Game crashes every time I try to upgrade my ship to T3. Lost all my resources twice now. Completely broken.", lang: "en", country: "US", appVersion: "1.38.2", category: "bug", subcategory: "crash", sentiment: "negative", themes: ["Performance & Stability Issues", "Crashes & Technical Bugs"], severity: 4, hasReply: false, createdAt: "2026-02-09T07:00:00Z" },
  { id: "r12", productId: "pirate-ships", rating: 1, text: "Too much server issue, after a single battle I'm having problem with server, even if I'm using 5G, I have to restart the game again.", lang: "en", country: "IN", appVersion: "1.38.2", category: "bug", subcategory: "server", sentiment: "negative", themes: ["Server Performance & Loading Issues"], severity: 4, hasReply: false, createdAt: "2026-02-10T06:00:00Z" },
  { id: "r13", productId: "pirate-ships", rating: 2, text: "Freezes constantly during battles. My phone is brand new with plenty of RAM. This isn't a device issue, it's a game issue.", lang: "en", country: "US", appVersion: "1.38.2", category: "bug", subcategory: "performance", sentiment: "negative", themes: ["Performance & Stability Issues"], severity: 4, hasReply: true, createdAt: "2026-02-08T18:00:00Z" },
  { id: "r14", productId: "pirate-ships", rating: 1, text: "Server hangs and blank chest rewards after watching ads. I watch a 30 second ad and get nothing. Fix your game!", lang: "en", country: "GB", appVersion: "1.38.2", category: "bug", subcategory: "rewards", sentiment: "negative", themes: ["Server Performance & Loading Issues", "Crashes & Technical Bugs"], severity: 4, hasReply: false, createdAt: "2026-02-09T13:00:00Z" },
  { id: "r15", productId: "pirate-ships", rating: 3, text: "Game disconnects from server a lot. Otherwise it's decent but the connectivity really ruins the experience during clan wars.", lang: "en", country: "US", appVersion: "1.38.2", category: "bug", subcategory: "connection", sentiment: "mixed", themes: ["Server & Connection Issues"], severity: 3, hasReply: false, createdAt: "2026-02-07T20:00:00Z" },
  { id: "r16", productId: "pirate-ships", rating: 5, text: "Addictive! Very little ads in the beginning. Fun pirate game with great auto-battle system.", lang: "en", country: "US", appVersion: "1.38.2", category: "praise", subcategory: "gameplay", sentiment: "positive", themes: ["Overall Positive Reception"], severity: 1, hasReply: false, createdAt: "2026-02-10T15:00:00Z" },
  { id: "r17", productId: "pirate-ships", rating: 5, text: "Fun game and challenging. Love building different ship combinations and testing them in battle.", lang: "en", country: "US", appVersion: "1.38.2", category: "praise", subcategory: "gameplay", sentiment: "positive", themes: ["Overall Positive Reception", "Core Gameplay & Fun"], severity: 1, hasReply: false, createdAt: "2026-02-10T10:00:00Z" },
  { id: "r18", productId: "pirate-ships", rating: 5, text: "Yar mad fun! Best pirate game on mobile by far. The combat is satisfying.", lang: "en", country: "US", appVersion: "1.38.1", category: "praise", subcategory: "gameplay", sentiment: "positive", themes: ["Core Gameplay & Fun"], severity: 1, hasReply: false, createdAt: "2026-02-06T09:00:00Z" },
  { id: "r19", productId: "pirate-ships", rating: 5, text: "Like the auto battle system, also fun to switch units around and try different things. Great strategy game!", lang: "en", country: "CA", appVersion: "1.38.2", category: "praise", subcategory: "mechanics", sentiment: "positive", themes: ["Core Gameplay & Fun", "Gameplay Mechanics & Depth"], severity: 1, hasReply: false, createdAt: "2026-02-09T20:00:00Z" },
  { id: "r20", productId: "pirate-ships", rating: 5, text: "Good interasting game. Keeps me coming back every day.", lang: "en", country: "IN", appVersion: "1.38.2", category: "praise", subcategory: "general", sentiment: "positive", themes: ["Overall Game Quality & Enjoyment"], severity: 1, hasReply: false, createdAt: "2026-02-08T06:00:00Z" },
  { id: "r21", productId: "pirate-ships", rating: 5, text: "Wonderful game! My kids and I play together every evening.", lang: "en", country: "US", appVersion: "1.38.1", category: "praise", subcategory: "general", sentiment: "positive", themes: ["Overall Game Quality & Enjoyment"], severity: 1, hasReply: true, createdAt: "2026-02-05T11:00:00Z" },
  { id: "r22", productId: "pirate-ships", rating: 5, text: "Nice graphics easy to understand and play. Great for casual gaming sessions.", lang: "en", country: "PH", appVersion: "1.38.2", category: "praise", subcategory: "graphics", sentiment: "positive", themes: ["Graphics & Visual Design"], severity: 1, hasReply: false, createdAt: "2026-02-07T08:00:00Z" },
  { id: "r23", productId: "pirate-ships", rating: 5, text: "Nice mechanic. I love this but sometimes it getting difficult to break meta. Still a solid game.", lang: "en", country: "ID", appVersion: "1.38.2", category: "praise", subcategory: "mechanics", sentiment: "positive", themes: ["Gameplay Mechanics & Depth"], severity: 1, hasReply: false, createdAt: "2026-02-06T14:00:00Z" },
  { id: "r24", productId: "pirate-ships", rating: 2, text: "Слишком много рекламы после 15 уровня. Невозможно играть нормально. Каждый бой заканчивается рекламой.", lang: "ru", country: "RU", appVersion: "1.38.2", category: "complaint", subcategory: "ads", sentiment: "negative", themes: ["Excessive & Intrusive Ads"], severity: 4, hasReply: false, createdAt: "2026-02-09T10:00:00Z" },
  { id: "r25", productId: "pirate-ships", rating: 1, text: "Игра вылетает при апгрейде корабля. Потерял все ресурсы. Верните мне мои монеты!", lang: "ru", country: "RU", appVersion: "1.38.2", category: "bug", subcategory: "crash", sentiment: "negative", themes: ["Crashes & Technical Bugs", "Performance & Stability Issues"], severity: 4, hasReply: false, createdAt: "2026-02-10T08:00:00Z" },
  { id: "r26", productId: "pirate-ships", rating: 1, text: "Матчмейкинг просто ужасный. Мой 25 уровень против 35+. Как играть то?", lang: "ru", country: "RU", appVersion: "1.38.2", category: "complaint", subcategory: "matchmaking", sentiment: "negative", themes: ["Matchmaking & Fair Play", "Pay-to-Win Mechanics"], severity: 4, hasReply: false, createdAt: "2026-02-08T16:00:00Z" },
  { id: "r27", productId: "pirate-ships", rating: 5, text: "Отличная игра! Залипательная. Играю уже месяц и не могу остановиться.", lang: "ru", country: "RU", appVersion: "1.38.2", category: "praise", subcategory: "gameplay", sentiment: "positive", themes: ["Overall Positive Reception"], severity: 1, hasReply: false, createdAt: "2026-02-07T12:00:00Z" },
  { id: "r28", productId: "pirate-ships", rating: 1, text: "Zu viele Werbungen. Nach jedem Kampf 30 Sekunden Werbung. Deinstalliert.", lang: "de", country: "DE", appVersion: "1.38.2", category: "complaint", subcategory: "ads", sentiment: "negative", themes: ["Excessive & Intrusive Ads"], severity: 4, hasReply: false, createdAt: "2026-02-09T11:00:00Z" },
  { id: "r29", productId: "pirate-ships", rating: 5, text: "Tolles Spiel! Macht süchtig. Die Grafik ist auch ganz gut.", lang: "de", country: "DE", appVersion: "1.38.2", category: "praise", subcategory: "general", sentiment: "positive", themes: ["Overall Game Quality & Enjoyment", "Graphics & Visual Design"], severity: 1, hasReply: false, createdAt: "2026-02-06T10:00:00Z" },
  { id: "r30", productId: "pirate-ships", rating: 1, text: "Jogo trava toda hora. Perdi meus recursos por causa de crash no meio da batalha.", lang: "pt", country: "BR", appVersion: "1.38.2", category: "bug", subcategory: "crash", sentiment: "negative", themes: ["Crashes & Technical Bugs"], severity: 4, hasReply: false, createdAt: "2026-02-10T03:00:00Z" },
  { id: "r31", productId: "pirate-ships", rating: 5, text: "Jogo muito bom! Viciante demais. Recomendo para quem gosta de estratégia.", lang: "pt", country: "BR", appVersion: "1.38.2", category: "praise", subcategory: "gameplay", sentiment: "positive", themes: ["Overall Positive Reception"], severity: 1, hasReply: false, createdAt: "2026-02-08T22:00:00Z" },
  { id: "r32", productId: "pirate-ships", rating: 2, text: "Loading screen takes forever. I spend more time staring at loading than actually playing the game.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "performance", sentiment: "negative", themes: ["Loading Times & Performance"], severity: 2, hasReply: false, createdAt: "2026-02-10T17:00:00Z" },
  { id: "r33", productId: "pirate-ships", rating: 4, text: "Fun game but events are way too hard for new players. The event rewards are only accessible to whales.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "events", sentiment: "mixed", themes: ["Event Balance Issues"], severity: 3, hasReply: false, createdAt: "2026-02-09T19:00:00Z" },
  { id: "r34", productId: "pirate-ships", rating: 4, text: "Would love to see more ship types and maybe some kind of alliance wars feature. The core game is great though!", lang: "en", country: "US", appVersion: "1.38.2", category: "feature", subcategory: "content", sentiment: "positive", themes: ["Content & Feature Requests"], severity: 2, hasReply: true, createdAt: "2026-02-08T14:00:00Z" },
  { id: "r35", productId: "pirate-ships", rating: 5, text: "Please add account backup option! I love this game and would hate to lose my progress.", lang: "en", country: "US", appVersion: "1.38.1", category: "feature", subcategory: "account", sentiment: "positive", themes: ["Account & Data Backup"], severity: 3, hasReply: false, createdAt: "2026-02-06T16:00:00Z" },
  { id: "r36", productId: "pirate-ships", rating: 1, text: "Battle logic makes no sense. My T3 ship with full upgrades loses to a base T2 ship. The combat calculations are broken.", lang: "en", country: "US", appVersion: "1.38.2", category: "bug", subcategory: "combat", sentiment: "negative", themes: ["Battle Logic & Combat Bugs"], severity: 4, hasReply: false, createdAt: "2026-02-09T08:00:00Z" },
  { id: "r37", productId: "pirate-ships", rating: 1, text: "I'm convinced the PvP is fake. The battles feel rigged to make you lose and spend money.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "combat", sentiment: "negative", themes: ["Battle Logic & Combat Bugs", "Pay-to-Win Mechanics"], severity: 4, hasReply: false, createdAt: "2026-02-08T21:00:00Z" },
  { id: "r38", productId: "pirate-ships", rating: 2, text: "Game balance and progression issues after the last update. Used to be fun, now it's a grind.", lang: "en", country: "GB", appVersion: "1.38.2", category: "complaint", subcategory: "balance", sentiment: "negative", themes: ["Game Balance & Progression Issues"], severity: 3, hasReply: false, createdAt: "2026-02-08T11:00:00Z" },
  { id: "r39", productId: "pirate-ships", rating: 4, text: "The grinding is real but honestly I don't mind it. The gameplay loop is satisfying enough to keep me playing.", lang: "en", country: "US", appVersion: "1.38.2", category: "praise", subcategory: "gameplay", sentiment: "mixed", themes: ["Grinding & Time Investment"], severity: 2, hasReply: false, createdAt: "2026-02-07T18:00:00Z" },
  { id: "r40", productId: "pirate-ships", rating: 5, text: "It's pretty simple and fun. Great for short gaming sessions on the bus.", lang: "en", country: "US", appVersion: "1.38.2", category: "praise", subcategory: "casual", sentiment: "positive", themes: ["Core Gameplay & Fun"], severity: 1, hasReply: false, createdAt: "2026-02-07T07:00:00Z" },
  { id: "r41", productId: "pirate-ships", rating: 1, text: "Не могу войти в игру после обновления. Черный экран и вылет. Samsung Galaxy S23.", lang: "ru", country: "RU", appVersion: "1.38.2", category: "bug", subcategory: "crash", sentiment: "negative", themes: ["Performance & Stability Issues", "Crashes & Technical Bugs"], severity: 5, hasReply: false, createdAt: "2026-02-10T09:30:00Z" },
  { id: "r42", productId: "pirate-ships", rating: 1, text: "Security concern - the game asks for way too many permissions. Why does a pirate game need my contacts?", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "security", sentiment: "negative", themes: ["Security & Trust Concerns"], severity: 2, hasReply: false, createdAt: "2026-02-06T13:00:00Z" },
  { id: "r43", productId: "pirate-ships", rating: 5, text: "This game needs more love. Add clan battles and more ship customization. 5 stars for now!", lang: "en", country: "AU", appVersion: "1.38.2", category: "feature", subcategory: "content", sentiment: "positive", themes: ["Content & Feature Requests"], severity: 2, hasReply: false, createdAt: "2026-02-09T22:00:00Z" },
  { id: "r44", productId: "pirate-ships", rating: 5, text: "El mejor juego de piratas en móvil. Me encanta la estrategia de combate.", lang: "es", country: "MX", appVersion: "1.38.2", category: "praise", subcategory: "gameplay", sentiment: "positive", themes: ["Overall Positive Reception"], severity: 1, hasReply: false, createdAt: "2026-02-07T15:00:00Z" },
  { id: "r45", productId: "pirate-ships", rating: 1, text: "Las compras son ridículas. $16 para quitar anuncios? Es una broma?", lang: "es", country: "MX", appVersion: "1.38.2", category: "complaint", subcategory: "monetization", sentiment: "negative", themes: ["Aggressive Monetization & Ad Strategy"], severity: 4, hasReply: false, createdAt: "2026-02-09T14:00:00Z" },
  { id: "r46", productId: "pirate-ships", rating: 5, text: "Super Spiel. Mache ich jeden Tag. Piraten sind cool!", lang: "de", country: "AT", appVersion: "1.38.1", category: "praise", subcategory: "general", sentiment: "positive", themes: ["Overall Positive Reception"], severity: 1, hasReply: false, createdAt: "2026-02-05T09:00:00Z" },
  { id: "r47", productId: "pirate-ships", rating: 2, text: "The UI needs polish. Buttons are too small, text overlaps on smaller screens. Hard to navigate menus.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "ui", sentiment: "negative", themes: ["UX & Polish"], severity: 2, hasReply: false, createdAt: "2026-02-08T13:00:00Z" },
  { id: "r48", productId: "pirate-ships", rating: 5, text: "Great game with lots of potential. The progression feels rewarding when you unlock new ship classes.", lang: "en", country: "US", appVersion: "1.38.2", category: "praise", subcategory: "progression", sentiment: "positive", themes: ["Progression & Gameplay Pacing"], severity: 1, hasReply: false, createdAt: "2026-02-10T20:00:00Z" },
  { id: "r49", productId: "pirate-ships", rating: 5, text: "Не могу оплатить через Мир. Добавьте пожалуйста альтернативные способы оплаты.", lang: "ru", country: "RU", appVersion: "1.38.2", category: "feature", subcategory: "payment", sentiment: "neutral", themes: ["Regional Payment Support"], severity: 2, hasReply: false, createdAt: "2026-02-07T11:00:00Z" },
  { id: "r50", productId: "pirate-ships", rating: 1, text: "This game is designed to waste your time. The more you play the more boring it gets. Uninstalling.", lang: "en", country: "US", appVersion: "1.38.2", category: "complaint", subcategory: "design", sentiment: "negative", themes: ["Game Design & Engagement"], severity: 2, hasReply: false, createdAt: "2026-02-06T20:00:00Z" },
];

// ── Clusters ──
export const clusters: Cluster[] = [
  {
    id: "cl-1",
    title: "Aggressive Monetization & Forced Ads",
    summary: "Players report predatory ad practices after level 10-15, including unskippable 30-second ads after every battle and a $16 ad-removal package. Some users report unauthorized repeat charges on credit cards after in-app purchases.",
    severity: 5,
    volume24h: 4,
    volume7d: 14,
    trend: 45,
    ratingAvg: 1.2,
    topLangs: ["en", "ru", "es"],
    topCountries: ["US", "RU", "MX"],
    topVersions: ["1.38.2"],
    firstSeen: "2026-01-20T00:00:00Z",
    lastSeen: "2026-02-10T14:32:00Z",
    status: "active",
    reviewIds: ["r1", "r2", "r3", "r4", "r9", "r10", "r24", "r28", "r45"],
    recommendedAction: "Immediately audit ad frequency, cap to 1 per 5 battles. Investigate unauthorized charge reports — potential legal/trust risk.",
  },
  {
    id: "cl-2",
    title: "Pay-to-Win & Matchmaking Imbalance",
    summary: "Free-to-play progression becomes nearly impossible at mid-game. T3+ ships cost 2M+ currency while battles yield 10K. Matchmaking pairs low-level F2P players against whales 6+ levels higher. Multiple players report PvP feels rigged.",
    severity: 4,
    volume24h: 3,
    volume7d: 12,
    trend: 30,
    ratingAvg: 1.4,
    topLangs: ["en", "ru"],
    topCountries: ["US", "IN", "RU", "GB"],
    topVersions: ["1.38.2"],
    firstSeen: "2026-01-15T00:00:00Z",
    lastSeen: "2026-02-10T06:00:00Z",
    status: "active",
    reviewIds: ["r5", "r6", "r7", "r8", "r26", "r37", "r38"],
    recommendedAction: "Rebalance F2P currency rewards (+50%), implement skill-based matchmaking, reduce late-game ship costs. Audit matchmaking algorithm in v1.38.2.",
  },
  {
    id: "cl-3",
    title: "Crashes & Server Instability",
    summary: "Frequent crashes during ship upgrades and battles, server disconnects post-battle even on 5G, blank chest rewards after watching ads. Issue escalated after v1.38.2 release.",
    severity: 4,
    volume24h: 3,
    volume7d: 10,
    trend: 60,
    ratingAvg: 1.3,
    topLangs: ["en", "ru", "pt"],
    topCountries: ["US", "RU", "BR", "IN"],
    topVersions: ["1.38.2"],
    firstSeen: "2026-02-07T00:00:00Z",
    lastSeen: "2026-02-10T09:30:00Z",
    status: "active",
    reviewIds: ["r11", "r12", "r13", "r14", "r15", "r25", "r30", "r41"],
    recommendedAction: "Hotfix: investigate post-battle server sync logic and ship upgrade crash. Profile memory usage on mid-range devices. Priority: v1.38.3 patch.",
  },
  {
    id: "cl-4",
    title: "Battle Logic & Combat Bugs",
    summary: "Players report T3 fully-upgraded ships losing to base T2 ships. Combat calculations appear broken or inconsistent. Multiple users suspect PvP is rigged.",
    severity: 4,
    volume24h: 1,
    volume7d: 4,
    trend: 15,
    ratingAvg: 1.0,
    topLangs: ["en"],
    topCountries: ["US"],
    topVersions: ["1.38.2"],
    firstSeen: "2026-02-05T00:00:00Z",
    lastSeen: "2026-02-09T08:00:00Z",
    status: "active",
    reviewIds: ["r36", "r37"],
    recommendedAction: "Investigation: audit combat formula in v1.38.2. Verify tier multiplier calculations. Publish transparent combat math documentation.",
  },
  {
    id: "cl-5",
    title: "Event Balance Issues",
    summary: "Events are too hard for new/mid-level players, with rewards only accessible to high-spenders. Creates frustration among F2P player base.",
    severity: 3,
    volume24h: 0,
    volume7d: 3,
    trend: -10,
    ratingAvg: 2.5,
    topLangs: ["en"],
    topCountries: ["US", "GB"],
    topVersions: ["1.38.2"],
    firstSeen: "2026-01-28T00:00:00Z",
    lastSeen: "2026-02-09T19:00:00Z",
    status: "monitoring",
    reviewIds: ["r33"],
    recommendedAction: "Adjust event difficulty scaling. Add tiered rewards accessible to mid-level players.",
  },
  {
    id: "cl-6",
    title: "UX & Polish Issues",
    summary: "Small buttons, text overlap on smaller screens, difficult menu navigation. Reported primarily on phones with smaller displays.",
    severity: 2,
    volume24h: 0,
    volume7d: 2,
    trend: 0,
    ratingAvg: 2.5,
    topLangs: ["en"],
    topCountries: ["US"],
    topVersions: ["1.38.2"],
    firstSeen: "2026-02-01T00:00:00Z",
    lastSeen: "2026-02-08T13:00:00Z",
    status: "monitoring",
    reviewIds: ["r47"],
    recommendedAction: "QA pass on responsive layout for small-screen devices. Increase tap target sizes.",
  },
  {
    id: "cl-7",
    title: "Login & Authentication Failures",
    summary: "Critical: Players unable to launch the game after v1.38.2 update. Black screen followed by crash on Samsung Galaxy S23 and similar devices.",
    severity: 5,
    volume24h: 1,
    volume7d: 2,
    trend: 100,
    ratingAvg: 1.0,
    topLangs: ["ru"],
    topCountries: ["RU"],
    topVersions: ["1.38.2"],
    firstSeen: "2026-02-10T00:00:00Z",
    lastSeen: "2026-02-10T09:30:00Z",
    status: "active",
    reviewIds: ["r41"],
    recommendedAction: "Hotfix: reproduce black screen on Samsung Galaxy S23 with v1.38.2. Check device-specific compatibility. Track login error rates over 72h.",
  },
];

// ── Alerts ──
export const alerts: Alert[] = [
  {
    id: "al-1",
    type: "new_cluster",
    severity: "critical",
    title: "Login failures after v1.38.2",
    description: "New critical cluster detected: players unable to launch game after update. Black screen + crash on Samsung devices.",
    metric: "login_failures",
    baseline: 0,
    current: 2,
    clusterId: "cl-7",
    detectedAt: "2026-02-10T10:00:00Z",
    status: "active",
  },
  {
    id: "al-2",
    type: "spike",
    severity: "high",
    title: "Matchmaking complaints spike",
    description: "Matchmaking & balance complaints spiked to 5 reports in 48h window (baseline: ~1/day). Correlates with v1.38.2 release.",
    metric: "matchmaking_complaints",
    baseline: 1,
    current: 5,
    clusterId: "cl-2",
    detectedAt: "2026-02-09T08:00:00Z",
    status: "active",
  },
  {
    id: "al-3",
    type: "spike",
    severity: "high",
    title: "Crash reports surge post-update",
    description: "Crash and server instability reports increased 3x after v1.38.2 release. 10 reports in 7 days vs baseline of 3.",
    metric: "crash_reports",
    baseline: 3,
    current: 10,
    clusterId: "cl-3",
    detectedAt: "2026-02-08T12:00:00Z",
    status: "acknowledged",
  },
  {
    id: "al-4",
    type: "rating_drop",
    severity: "medium",
    title: "Rating trending downward",
    description: "Average rating dropped from 4.52 to 4.49 over the past week. 1-2 star reviews increased from 10% to 12% share.",
    metric: "avg_rating",
    baseline: 4.52,
    current: 4.49,
    detectedAt: "2026-02-10T00:00:00Z",
    status: "active",
  },
  {
    id: "al-5",
    type: "region_outbreak",
    severity: "medium",
    title: "RU region negative review surge",
    description: "Negative reviews from Russia increased by 4x in the past 3 days. Primarily crash reports and matchmaking complaints.",
    metric: "ru_negative_reviews",
    baseline: 2,
    current: 8,
    detectedAt: "2026-02-10T06:00:00Z",
    status: "active",
  },
  {
    id: "al-6",
    type: "spike",
    severity: "low",
    title: "Ad complaint volume elevated",
    description: "Ad-related complaints running at 2x baseline. Not yet at critical threshold but trending upward.",
    metric: "ad_complaints",
    baseline: 4,
    current: 8,
    detectedAt: "2026-02-09T14:00:00Z",
    status: "acknowledged",
  },
];

// ── Action Items ──
export const actionItems: ActionItem[] = [
  {
    id: "act-1",
    type: "hotfix",
    title: "Fix login crash on Samsung devices",
    rationale: "Multiple crash reports on Galaxy S23 with v1.38.2, suspected initialization race condition.",
    importance: 10,
    relatedClusterId: "cl-7",
  },
  {
    id: "act-2",
    type: "hotfix",
    title: "Patch server sync post-battle",
    rationale: "Server-side battle result sync failures on 5G connections causing data loss.",
    importance: 9,
    relatedClusterId: "cl-3",
  },
  {
    id: "act-3",
    type: "escalation",
    title: "Investigate unauthorized credit card charges",
    rationale: "Trust risk — users report unauthorized charges after single purchase. Potential payment flow bug.",
    importance: 9,
    relatedClusterId: "cl-1",
  },
  {
    id: "act-4",
    type: "investigation",
    title: "Audit matchmaking algorithm v1.38.2",
    rationale: "Fairness complaints spiked after v1.38.2 update, matchmaking parameters may have shifted.",
    importance: 6,
    relatedClusterId: "cl-2",
  },
  {
    id: "act-5",
    type: "faq",
    title: "Update FAQ: ad removal options",
    rationale: "Recurring complaints about ad frequency and $16 package value — clear communication gap.",
    importance: 4,
    relatedClusterId: "cl-1",
  },
];
